name: Go

on: [push, pull_request]

jobs:
  build:
    name: Go Build

    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.5'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
 
    - name: Build go programm
      run: go build
